name: example_flutter
description: An example project for flutter-desktop-embedding.

environment:
  sdk: ">=2.0.0 <3.0.0"
  # The example interacts with build scripts on the Flutter side that are not
  # yet stable, so it requires a very recent version of Flutter.
  # This version will increase regularly as the build scripts change.
  flutter: ">=1.5.9-pre.270"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0
  splashscreen: ^1.2.0
  file_picker: ^1.3.8
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # See https://github.com/flutter/flutter/wiki/Desktop-shells#fonts
