# Generated by Django 3.0.5 on 2020-04-27 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0003_renter_vacancystatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='vacancy_status',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='renter',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Select Gender', max_length=100),
        ),
        migrations.DeleteModel(
            name='VacancyStatus',
        ),
    ]
