# Generated by Django 3.0.5 on 2020-04-27 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0005_flat_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='floor',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9')], default=1),
        ),
        migrations.CreateModel(
            name='RentIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('rent', models.IntegerField(default=10000)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('flat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmanager.Flat')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmanager.Renter')),
            ],
        ),
    ]
