# Generated by Django 3.0.5 on 2020-04-27 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0006_auto_20200427_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], default='January', max_length=100)),
                ('year', models.IntegerField(default=2020)),
                ('electricity_bill', models.IntegerField(default=2020)),
                ('gas_bill', models.IntegerField(default=2020)),
                ('water_bill', models.IntegerField(default=2020)),
                ('service_charge', models.IntegerField(default=2020)),
                ('paid', models.BooleanField(default=False)),
                ('issue_date', models.DateField()),
                ('total_payable', models.FloatField(default=0)),
                ('rent_issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rentmanager.RentIssue')),
            ],
        ),
    ]
