# Generated by Django 3.0.5 on 2020-04-28 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0008_auto_20200427_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
