# Generated by Django 3.0.5 on 2020-04-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentmanager', '0009_auto_20200428_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='vacancy_status',
            field=models.BooleanField(default=True),
        ),
    ]
